name: Generate a build and push to another branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Step to install all dependencies legacy-peer-deps is used to avoid peer dependencies warnings
      - name: Install all dependencies
        run: npm install --legacy-peer-deps

      # Step to run tests
      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      # Step to create the branch if it doesn't exist
      - name: Ensure build branch exists
        run: |
          git fetch origin
          if git show-ref --verify --quiet refs/heads/build; then
            echo "Branch 'build' already exists."
            git checkout build
          else
            echo "Branch 'build' does not exist. Creating it."
            git checkout -b build
          fi
        shell: bash

      - name: Push to build branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: 'Build: ({sha}) {msg}' # The commit message
